baker.types {
  "java.util.List" = "com.ing.baker.types.reflect.modules.JavaModules$ListModule"
  "java.util.Set" = "com.ing.baker.types.reflect.modules.JavaModules$SetModule"
  "java.util.Map" = "com.ing.baker.types.reflect.modules.JavaModules$MapModule"
  "java.util.Optional" = "com.ing.baker.types.reflect.modules.JavaModules$OptionalModule"

  "java.lang.Enum" = "com.ing.baker.types.reflect.modules.EnumModule"

  "scala.collection.immutable.List" = "com.ing.baker.types.reflect.modules.ScalaModules$ListModule"
  "scala.collection.immutable.Set" = "com.ing.baker.types.reflect.modules.ScalaModules$SetModule"
  "scala.collection.immutable.Map" = "com.ing.baker.types.reflect.modules.ScalaModules$MapModule"
  "scala.Option" = "com.ing.baker.types.reflect.modules.ScalaModules$OptionModule"

  "java.lang.Object" = "com.ing.baker.types.reflect.modules.PojoModule"
}